package dev.jombi.hangulkt

private val QWERTY_KEYBOARD_MAP = mapOf(
    'q' to 'ㅂ',
    'Q' to 'ㅃ',
    'w' to 'ㅈ',
    'W' to 'ㅉ',
    'e' to 'ㄷ',
    'E' to 'ㄸ',
    'r' to 'ㄱ',
    'R' to 'ㄲ',
    't' to 'ㅅ',
    'T' to 'ㅆ',
    'y' to 'ㅛ',
    'Y' to 'ㅛ',
    'u' to 'ㅕ',
    'U' to 'ㅕ',
    'i' to 'ㅑ',
    'I' to 'ㅑ',
    'o' to 'ㅐ',
    'O' to 'ㅒ',
    'p' to 'ㅔ',
    'P' to 'ㅖ',
    'a' to 'ㅁ',
    'A' to 'ㅁ',
    's' to 'ㄴ',
    'S' to 'ㄴ',
    'd' to 'ㅇ',
    'D' to 'ㅇ',
    'f' to 'ㄹ',
    'F' to 'ㄹ',
    'g' to 'ㅎ',
    'G' to 'ㅎ',
    'h' to 'ㅗ',
    'H' to 'ㅗ',
    'j' to 'ㅓ',
    'J' to 'ㅓ',
    'k' to 'ㅏ',
    'K' to 'ㅏ',
    'l' to 'ㅣ',
    'L' to 'ㅣ',
    'z' to 'ㅋ',
    'Z' to 'ㅋ',
    'x' to 'ㅌ',
    'X' to 'ㅌ',
    'c' to 'ㅊ',
    'C' to 'ㅊ',
    'v' to 'ㅍ',
    'V' to 'ㅍ',
    'b' to 'ㅠ',
    'B' to 'ㅠ',
    'n' to 'ㅜ',
    'N' to 'ㅜ',
    'm' to 'ㅡ',
    'M' to 'ㅡ',
)

public fun convertQwertyToAlphabet(word: String): String {
    return word.map { if (it in QWERTY_KEYBOARD_MAP) QWERTY_KEYBOARD_MAP[it] else it }.joinToString("")
}
